media:
  input: static/img
  output: /img

content:
  - name: content
    label: Content
    type: collection
    path: editor
    filename: "{slug}.mdx"
    subfolders: true
    fields:
      - name: slug
        label: Slug
        type: string
        required: true

      - name: sidebar_label
        label: Sidebar Label
        type: string
        required: true

      - name: sidebar_position
        label: Sidebar Position
        type: number

      - name: body
        label: Body
        type: rich-text

  - name: categories
    label: Categories
    type: collection
    path: editor
    filename: "_category_.yml"
    subfolders: true
    fields:
      - name: label
        label: Label
        type: string
        required: true

      - name: position
        label: Position
        type: number
