import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  default: [
    {
      type: "category",
      label: "Docs",
      items: [{ type: "autogenerated", dirName: "docs" }],
    },

    {
      type: "category",
      label: "FAQs",
      items: [{ type: "autogenerated", dirName: "faq" }],
    },

    {
      type: "category",
      label: "Troubleshooting",
      items: [{ type: "autogenerated", dirName: "troubleshooting" }],
    },

    {
      type: "category",
      label: "Comparisons",
      items: [{ type: "autogenerated", dirName: "comparisons" }],
    },

    {
      type: "category",
      label: "Changelog",
      items: [{ type: "autogenerated", dirName: "changelog" }],
    },
  ],
};

export default sidebars;
